# Generated by Django 6.0.2 on 2026-02-08 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlavorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acidity', models.IntegerField(default=0)),
                ('body', models.IntegerField(default=0)),
                ('sweetness', models.IntegerField(default=0)),
                ('bitterness', models.IntegerField(default=0)),
                ('aroma', models.IntegerField(default=0)),
                ('aftertaste', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tarot_cards/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('flavor_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.flavorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('acidity_score', models.IntegerField(default=0)),
                ('body_score', models.IntegerField(default=0)),
                ('sweetness_score', models.IntegerField(default=0)),
                ('bitterness_score', models.IntegerField(default=0)),
                ('aroma_score', models.IntegerField(default=0)),
                ('aftertaste_score', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.question')),
            ],
        ),
        migrations.CreateModel(
            name='UserTasteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flavor_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.flavorprofile')),
            ],
        ),
    ]
