# Generated by Django 6.0.1 on 2026-02-01 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acidity', models.FloatField(default=0.0, help_text='Acidic taste (0-10)')),
                ('body', models.FloatField(default=0.0, help_text='Body/Weight (0-10)')),
                ('sweetness', models.FloatField(default=0.0, help_text='Sweetness (0-10)')),
                ('bitterness', models.FloatField(default=0.0, help_text='Bitterness (0-10)')),
                ('aroma', models.FloatField(default=0.0, help_text='Aroma intensity (0-10)')),
                ('texture', models.FloatField(default=0.0, help_text='Texture/Carbonation (0-10)')),
                ('caffeine', models.FloatField(default=0.0, help_text='Caffeine content (mg or relative scale)')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('COFFEE', 'Coffee'), ('TEA', 'Tea'), ('FOOD', 'Food'), ('BEVERAGE', 'Other Beverage')], default='COFFEE', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acidity', models.FloatField(default=0.0, help_text='Acidic taste (0-10)')),
                ('body', models.FloatField(default=0.0, help_text='Body/Weight (0-10)')),
                ('sweetness', models.FloatField(default=0.0, help_text='Sweetness (0-10)')),
                ('bitterness', models.FloatField(default=0.0, help_text='Bitterness (0-10)')),
                ('aroma', models.FloatField(default=0.0, help_text='Aroma intensity (0-10)')),
                ('texture', models.FloatField(default=0.0, help_text='Texture/Carbonation (0-10)')),
                ('caffeine', models.FloatField(default=0.0, help_text='Caffeine content (mg or relative scale)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
