# Generated by Django 6.0.2 on 2026-02-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_expert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('scale', 'Scale (1-5)'), ('binary', 'Yes/No')], default='multiple_choice', max_length=20),
        ),
    ]
